### PR TITLE
Optimization of Dockerfile

### PR DESCRIPTION
**Pull request by madduci**
Chained some RUN commands together to optimize the final Docker image, cleaning up also cache.

### CODE REVIEW

**Comment by patricia-gallardo** [comment]
Since this is an intro to Linux class I don't feel this adds to the understand-ability. Are you using this project?

**Comment by madduci** [comment]
Not yet, but I've noticed that there are multiple RUN commands, making the final image bigger than it needs to be and it might cause slow starts on computers that are not so performant.
I've added also `echo` to print out what's going on.

**Comment by patricia-gallardo** [comment]
Then I think I'll leave it as it is for now, I have enough things to explain to my class :D Thanks, though!

**Comment by madduci** [comment]
Ok! 
At the end, I just chained commands together with `&&` and `\` stands for new line in the chain.

Also VS Code supports remote development: https://code.visualstudio.com/docs/remote/remote-overview (I've read the remote-coding post on your personal website with CLion)

**Comment by patricia-gallardo** [comment]
Yes, this file is for a particular setup and they are already using Jetbrains products in their other classes.

**Pull request closed without merging**
